version: "3.3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/dynamic:/dynamic
      - ./config/certs:/certs
      - ./acme.json:/acme.json
      - ./log:/log
    labels:
      - "traefik.enable=true"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: traefik-portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"

volumes:
  portainer_data:

networks:
  traefik_proxy:
    external: true